import type { DevopsInfraCategory } from '../types/devops-infra';

export const devopsInfraCategoryKeywords: Record<DevopsInfraCategory, readonly string[]> = {
  'k8s-containers': [
    'kubernetes',
    'k8s',
    'kubectl',
    'helm',
    'pod',
    'container',
    'crashloopbackoff',
    'oomkilled',
    'imagepullbackoff',
    'namespace',
    'deployment',
    'statefulset',
    'docker',
    'containerd',
    'cri',
  ],
  'cloud-aws': [
    'aws',
    'amazon web services',
    'ec2',
    's3',
    'eks',
    'iam',
    'lambda',
    'rds',
    'cloudformation',
    'route53',
    'accessdenied',
    'cloudwatch',
  ],
  'cloud-gcp': [
    'gcp',
    'google cloud',
    'gke',
    'cloud run',
    'cloud storage',
    'bigquery',
    'compute engine',
    'cloud sql',
    'stackdriver',
  ],
  'cloud-azure': [
    'azure',
    'aks',
    'arm template',
    'blob storage',
    'virtual machine',
    'entra',
    'active directory',
    'azure devops',
    'resource group',
  ],
  'onprem-selfhosted': [
    'on-prem',
    'onprem',
    'self-hosted',
    'self hosted',
    'homelab',
    'bare metal',
    'proxmox',
    'vmware',
    'hyper-v',
    'datacenter',
    'colocation',
    'linux',
    'systemd',
  ],
  networking: [
    'network',
    'networking',
    'dns',
    'vpn',
    'wireguard',
    'firewall',
    'load balancer',
    'nginx',
    'apache',
    'haproxy',
    'cilium',
    'calico',
    'bgp',
    'tcp',
    'tls',
    'ssl',
    'ssh',
    'certificate',
    'cert expiry',
  ],
  'observability-sre': [
    'observability',
    'monitoring',
    'prometheus',
    'grafana',
    'alertmanager',
    'sre',
    'slo',
    'sli',
    'on-call',
    'incident response',
    'pagerduty',
    'datadog',
    'loki',
    'tracing',
  ],
  cicd: [
    'ci/cd',
    'cicd',
    'pipeline',
    'gitlab ci',
    'github actions',
    'jenkins',
    'argocd',
    'flux',
    'build',
    'deploy',
    'release',
    'artifact',
  ],
  'db-storage': [
    'database',
    'postgres',
    'postgresql',
    'mysql',
    'mongodb',
    'redis',
    'elasticsearch',
    'storage',
    'backup',
    'restore',
    'replication',
    'pvc',
    'persistent volume',
    'nfs',
    'ceph',
  ],
  'iam-secrets': [
    'iam',
    'rbac',
    'role',
    'policy',
    'permission',
    'secret',
    'secrets manager',
    'vault',
    'hashicorp vault',
    'sso',
    'oauth',
    'service account',
    'access key',
    'credential',
  ],
};

export const devopsInfraIncidentKeywords: readonly string[] = [
  'outage',
  'cve',
  'postmortem',
  'status page',
  'incident',
  'sự cố',
];

export const devopsInfraCloudEnvironmentKeywords: readonly string[] = [
  'eks',
  'gke',
  'aks',
  'aws',
  'gcp',
  'azure',
  'amazon web services',
  'google cloud',
  'microsoft azure',
  'cloud',
];

export const devopsInfraOnpremEnvironmentKeywords: readonly string[] = [
  'bare metal',
  'proxmox',
  'on-prem',
  'onprem',
  'self-hosted',
  'self hosted',
  'homelab',
];
