import type { PoliticsSearchQuery } from '../types/gold-politics';
import type { RssSourceConfig } from '../types/source';

export const goldPoliticsRssSources: RssSourceConfig[] = [
  {
    id: 'vnexpress-thoi-su',
    name: 'VnExpress Thời sự',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://vnexpress.net/thoi-su',
    feedUrl: 'https://vnexpress.net/rss/thoi-su.rss',
    includeUnmatched: true,
  },
  {
    id: 'vnexpress-the-gioi',
    name: 'VnExpress Thế giới',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://vnexpress.net/the-gioi',
    feedUrl: 'https://vnexpress.net/rss/the-gioi.rss',
    includeUnmatched: true,
  },
  {
    id: 'vnexpress-phap-luat',
    name: 'VnExpress Pháp luật',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://vnexpress.net/phap-luat',
    feedUrl: 'https://vnexpress.net/rss/phap-luat.rss',
    includeUnmatched: true,
  },
  {
    id: 'vnexpress-kinh-doanh',
    name: 'VnExpress Kinh doanh',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://vnexpress.net/kinh-doanh',
    feedUrl: 'https://vnexpress.net/rss/kinh-doanh.rss',
    includeUnmatched: true,
  },
  {
    id: 'thanhnien-chinh-tri',
    name: 'Thanh Niên Chính trị',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://thanhnien.vn/chinh-tri.htm',
    feedUrl: 'https://thanhnien.vn/rss/chinh-tri.rss',
    includeUnmatched: true,
  },
  {
    id: 'thanhnien-thoi-su',
    name: 'Thanh Niên Thời sự',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://thanhnien.vn/thoi-su.htm',
    feedUrl: 'https://thanhnien.vn/rss/thoi-su.rss',
    includeUnmatched: true,
  },
  {
    id: 'thanhnien-the-gioi',
    name: 'Thanh Niên Thế giới',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://thanhnien.vn/the-gioi.htm',
    feedUrl: 'https://thanhnien.vn/rss/the-gioi.rss',
    includeUnmatched: true,
  },
  {
    id: 'thanhnien-phong-su-dieu-tra',
    name: 'Thanh Niên Phóng sự Điều tra',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://thanhnien.vn/thoi-su/phong-su-dieu-tra.htm',
    feedUrl: 'https://thanhnien.vn/rss/thoi-su/phong-su--dieu-tra.rss',
    includeUnmatched: true,
  },
  {
    id: 'thanhnien-kinh-te',
    name: 'Thanh Niên Kinh tế',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://thanhnien.vn/kinh-te.htm',
    feedUrl: 'https://thanhnien.vn/rss/kinh-te.rss',
    includeUnmatched: true,
  },
  {
    id: 'tuoitre-thoi-su',
    name: 'Tuổi Trẻ Thời sự',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://tuoitre.vn/thoi-su.htm',
    feedUrl: 'https://tuoitre.vn/rss/thoi-su.rss',
    includeUnmatched: true,
  },
  {
    id: 'tuoitre-the-gioi',
    name: 'Tuổi Trẻ Thế giới',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://tuoitre.vn/the-gioi.htm',
    feedUrl: 'https://tuoitre.vn/rss/the-gioi.rss',
    includeUnmatched: true,
  },
  {
    id: 'tuoitre-phap-luat',
    name: 'Tuổi Trẻ Pháp luật',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://tuoitre.vn/phap-luat.htm',
    feedUrl: 'https://tuoitre.vn/rss/phap-luat.rss',
    includeUnmatched: true,
  },
  {
    id: 'tuoitre-kinh-doanh',
    name: 'Tuổi Trẻ Kinh doanh',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://tuoitre.vn/kinh-doanh.htm',
    feedUrl: 'https://tuoitre.vn/rss/kinh-doanh.rss',
    includeUnmatched: true,
  },
  {
    id: 'bbc-world',
    name: 'BBC World',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://www.bbc.com/news/world',
    feedUrl: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    includeUnmatched: true,
  },
  {
    id: 'guardian-world',
    name: 'The Guardian World',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://www.theguardian.com/world',
    feedUrl: 'https://www.theguardian.com/world/rss',
    includeUnmatched: true,
  },
  {
    id: 'guardian-politics',
    name: 'The Guardian Politics',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://www.theguardian.com/politics',
    feedUrl: 'https://www.theguardian.com/politics/rss',
    includeUnmatched: true,
  },
  {
    id: 'aljazeera-all',
    name: 'Al Jazeera',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://www.aljazeera.com',
    feedUrl: 'https://www.aljazeera.com/xml/rss/all.xml',
    includeUnmatched: true,
  },
];

export const politicsSearchQueries: PoliticsSearchQuery[] = [
  {
    key: 'vietnam-politics',
    text: 'chính trị Việt Nam lãnh đạo Quốc hội Chính phủ Vietnamese politics leaders',
  },
  {
    key: 'international-politics',
    text: 'chính trị quốc tế lãnh đạo chính phủ international politics world leaders',
  },
  {
    key: 'vietnam-leader-controversies',
    text: 'tranh cãi bê bối cáo buộc lãnh đạo Việt Nam Vietnamese leader controversy allegations',
  },
  {
    key: 'international-leader-controversies',
    text: 'tranh cãi lãnh đạo quốc tế international leader controversy scandal allegations',
  },
  {
    key: 'gold-market-drivers',
    text: 'giá vàng ngân hàng trung ương lãi suất USD gold central bank rates dollar drivers',
  },
  {
    key: 'facebook-leader-controversies',
    text: 'tranh cãi lãnh đạo chính trị leader controversy allegations site:facebook.com',
    discoveryHint: 'facebook',
  },
  {
    key: 'tiktok-leader-controversies',
    text: 'tranh cãi lãnh đạo chính trị leader controversy allegations site:tiktok.com',
    discoveryHint: 'tiktok',
  },
  {
    key: 'telegram-leader-controversies',
    text: 'tranh cãi lãnh đạo chính trị leader controversy allegations site:t.me',
    discoveryHint: 'telegram',
  },
];

export function buildPoliticsSearchQueries(maxQueries: number): PoliticsSearchQuery[] {
  return politicsSearchQueries.slice(0, Math.max(0, maxQueries));
}
