import { env } from './env';
import type { SourceConfig } from '../types/source';
import type { TopicKey } from '../types/topic';

const redditRssSource = (subreddit: string, slug: string, defaultTopics: TopicKey[]): SourceConfig => ({
  id: `reddit-${slug}`,
  name: `Reddit r/${subreddit}`,
  kind: 'rss',
  enabled: true,
  homepageUrl: `https://www.reddit.com/r/${subreddit}`,
  feedUrl: `https://www.reddit.com/r/${subreddit}/.rss?limit=10`,
  defaultTopics,
});

export const sources: SourceConfig[] = [
  {
    id: 'hn-rss',
    name: 'Hacker News',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://news.ycombinator.com',
    feedUrl: 'https://hnrss.org/frontpage',
  },
  {
    id: 'kubernetes-blog',
    name: 'Kubernetes Blog',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://kubernetes.io/blog/',
    feedUrl: 'https://kubernetes.io/feed.xml',
  },
  {
    id: 'x-search',
    name: 'X Search',
    kind: 'x-search',
    enabled: Boolean(env.X_BEARER_TOKEN),
    homepageUrl: 'https://x.com',
    bearerToken: env.X_BEARER_TOKEN,
    query: env.X_SEARCH_QUERY,
    maxResults: env.X_SEARCH_MAX_RESULTS,
  },
  {
    id: 'github-ai-repos',
    name: 'GitHub AI Repos',
    kind: 'github-repos',
    enabled: true,
    homepageUrl: 'https://github.com',
    token: env.GITHUB_TOKEN,
    query: env.GITHUB_AI_REPO_QUERY,
    maxResults: env.GITHUB_AI_REPO_MAX_RESULTS,
    lookbackDays: env.GITHUB_AI_REPO_LOOKBACK_DAYS,
  },
  redditRssSource('MachineLearning', 'machine-learning', ['ai']),
  redditRssSource('LocalLLaMA', 'local-llama', ['ai']),
  redditRssSource('OpenAI', 'openai', ['ai']),
  redditRssSource('artificial', 'artificial', ['ai']),
  redditRssSource('kubernetes', 'kubernetes', ['k8s']),
  redditRssSource('devops', 'devops', ['devops']),
  redditRssSource('cybersecurity', 'cybersecurity', ['security']),
  redditRssSource('aws', 'aws', ['cloud']),
  {
    id: 'google-security-blog',
    name: 'Google Security Blog',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://security.googleblog.com',
    feedUrl: 'https://security.googleblog.com/feeds/posts/default',
  },
  {
    id: 'aws-news-blog',
    name: 'AWS News Blog',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://aws.amazon.com/blogs/aws/',
    feedUrl: 'https://aws.amazon.com/blogs/aws/feed/',
  },
  {
    id: 'cncf-blog',
    name: 'CNCF Blog',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://www.cncf.io/blog/',
    feedUrl: 'https://www.cncf.io/feed/',
  },
  {
    id: 'devops-dot-com',
    name: 'DevOps.com',
    kind: 'rss',
    enabled: true,
    homepageUrl: 'https://devops.com',
    feedUrl: 'https://devops.com/feed/',
  },
  {
    id: 'the-hacker-news-html',
    name: 'The Hacker News',
    kind: 'html',
    enabled: true,
    homepageUrl: 'https://thehackernews.com',
    listUrl: 'https://thehackernews.com',
    selectors: {
      item: '.body-post',
      title: '.home-title',
      url: 'a.story-link',
      summary: '.home-desc',
      publishedAt: '.h-datetime',
      image: 'img',
    },
  },
];
